apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "udb-api.fullname" . }}-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "udb-api.fullname" . }}-artifacts
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.artifacts.size }}
