{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voyant-udb.name" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels: { app: {{ include "voyant-udb.name" . }}-redis }
  template:
    metadata:
      labels: { app: {{ include "voyant-udb.name" . }}-redis }
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          resources:
            limits: { memory: 256Mi, cpu: 200m }
            requests: { memory: 128Mi, cpu: 100m }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voyant-udb.name" . }}-redis
spec:
  selector:
    app: {{ include "voyant-udb.name" . }}-redis
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
