apiVersion: v1
kind: Service
metadata:
  name: {{ include "voyant-udb.name" . }}
  labels:
    app: {{ include "voyant-udb.name" . }}
spec:
  selector:
    app: {{ include "voyant-udb.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
