apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: udb
spec:
  replicas: 1
  selector:
    matchLabels: { app: redis }
  template:
    metadata:
      labels: { app: redis }
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          args: ["--appendonly", "yes"]
          resources:
            limits: { memory: "256Mi", cpu: "200m" }
            requests: { memory: "128Mi", cpu: "100m" }
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: udb
spec:
  selector: { app: redis }
  ports:
    - port: 6379
      targetPort: 6379
