apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: udb
spec:
  replicas: 1
  selector:
    matchLabels: { app: zookeeper }
  template:
    metadata:
      labels: { app: zookeeper }
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.9
          env:
            - { name: ALLOW_ANONYMOUS_LOGIN, value: "yes" }
          ports:
            - containerPort: 2181
          resources:
            limits: { memory: "512Mi", cpu: "300m" }
            requests: { memory: "256Mi", cpu: "100m" }
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: udb
spec:
  selector: { app: zookeeper }
  ports:
    - port: 2181
      targetPort: 2181
